exclusions:
- LICENSE.md
- CONTRIBUTING.md
- GitVersion.yml
- src/NServiceBus.snk
- src/NServiceBusTests.snk
- .github/SUPPORT.md
- .github/workflows/virus-scan.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/improvement_request.yml